name = "modice"
type = 'javascript'
account_id = ''
route = ''
zone_id = ''
usage_model = ''
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  { name = "MODICE", class_name = "DurableModice" }
]
